[package]
name = "sway-tab"
version = "1.0.0"
authors = ["Anonymous"]
edition = "2021"
description = "Alt-Tab daemon for Sway WM"
license = "MIT"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
futures-lite = "2"
swayipc-async = "3"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "signal"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
